services:
  web:
    build: .
    env_file: .env
    restart: always
    volumes:
      - db-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.services.html_classroom_monitor.loadbalancer.server.port=80"
      - "traefik.http.routers.html_classroom_monitor.rule=Host(`html.bf0.ch`)"
      - "traefik.http.routers.html_classroom_monitor.entrypoints=web"
      - "traefik.http.routers.html_classroom_monitor.middlewares=https_redirect"
      - "traefik.http.routers.html_classroom_monitor_secured.rule=Host(`html.bf0.ch`)"
      - "traefik.http.routers.html_classroom_monitor_secured.entrypoints=websecure"
      - "traefik.http.routers.html_classroom_monitor_secured.tls=true"
      - "traefik.http.routers.html_classroom_monitor_secured.tls.certresolver=myresolver"
    networks:
      - web
volumes:
   db-data:
     driver: local
networks:
  web:
    external: true